version: "3.8"

volumes:
     devrydata:
          name: devry-services-data
     apachehtml:
          name: apachehtml

services:
     devry-services:
          environment:
               TZ: "America/New_York"
           image: "ghcr.io/unofficial-devry-it/devrycommunity:latest"
          restart: "always"
          volumes:
               - devrydata:/app/Data:rw
               - apachehtml:/app/web:z